name: "test"
on: 
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.md'

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04] # macOS and Windows are expensive, so running test on linux only until we get rich.

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Caching cargo
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: awalsh128/cache-apt-pkgs-action@latest
      if: matrix.platform == 'ubuntu-22.04'
      with: 
        packages: libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
        version: ${{ matrix.platform }}
    - name: yarn install
      run: yarn install
    - name: lint
      run: yarn lint
    - name: build
      run: yarn tauri build
    - name: vitest
      run: yarn vitest run